/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workingwiththreads;

/**
 *
 * @author hp
 */
public class clocktest extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form clocktest
     */
    public clocktest() {
        initComponents();
        Thread obj=new Thread(this);
        obj.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clocktest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clocktest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clocktest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clocktest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clocktest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    int seconds=00;
    int minutes=00;
    int hours=00;
    try
    {
        while(true)
        {
            if((seconds==60)&&(minutes==5)&&(hours==4))
            {
                hours=00;
                minutes=00;
                seconds=00;
                jLabel1.setText(String.valueOf(hours));
                jLabel2.setText(String.valueOf(minutes));
                jLabel3.setText(String.valueOf(seconds));
                Thread.sleep(100);
            }
            else if((seconds==60)&&(minutes==5)&&(hours!=4))
            {
                hours=hours+1;
                minutes=00;
                seconds=00;
                jLabel1.setText(String.valueOf(hours));
                jLabel2.setText(String.valueOf(minutes));
                jLabel3.setText(String.valueOf(seconds));
                Thread.sleep(100);
            }
            else if((seconds==60)&&(minutes!=60))
            {
                minutes=minutes+1;
                seconds=00;
                jLabel1.setText(String.valueOf(hours));
                jLabel2.setText(String.valueOf(minutes));
                jLabel3.setText(String.valueOf(seconds));
                Thread.sleep(100);
            }
            else if((seconds!=60)&&(minutes!=5)&&(hours!=4))
            {
                jLabel1.setText(String.valueOf(hours));
                jLabel2.setText(String.valueOf(minutes));
                jLabel3.setText(String.valueOf(seconds));
                Thread.sleep(100);
            }
            seconds++;
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    }
}
